/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalisarFaturaRouteImport } from './routes/_authenticated/analisar-fatura'
import { Route as AuthenticatedConferenciaRouteImport } from './routes/_authenticated/conferencia'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedParcelasRouteImport } from './routes/_authenticated/parcelas'
import { Route as AuthenticatedVisaoFuturaRouteImport } from './routes/_authenticated/visao-futura'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as ApiAnalisarFaturaRouteImport } from './routes/api/analisar-fatura'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalisarFaturaRoute =
  AuthenticatedAnalisarFaturaRouteImport.update({
    id: '/analisar-fatura',
    path: '/analisar-fatura',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenciaRoute =
  AuthenticatedConferenciaRouteImport.update({
    id: '/conferencia',
    path: '/conferencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParcelasRoute = AuthenticatedParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoFuturaRoute =
  AuthenticatedVisaoFuturaRouteImport.update({
    id: '/visao-futura',
    path: '/visao-futura',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAnalisarFaturaRoute = ApiAnalisarFaturaRouteImport.update({
  id: '/api/analisar-fatura',
  path: '/api/analisar-fatura',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analisar-fatura': typeof AuthenticatedAnalisarFaturaRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/parcelas': typeof AuthenticatedParcelasRoute
  '/visao-futura': typeof AuthenticatedVisaoFuturaRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/api/analisar-fatura': typeof ApiAnalisarFaturaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analisar-fatura': typeof AuthenticatedAnalisarFaturaRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/parcelas': typeof AuthenticatedParcelasRoute
  '/visao-futura': typeof AuthenticatedVisaoFuturaRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/api/analisar-fatura': typeof ApiAnalisarFaturaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analisar-fatura': typeof AuthenticatedAnalisarFaturaRoute
  '/_authenticated/conferencia': typeof AuthenticatedConferenciaRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/parcelas': typeof AuthenticatedParcelasRoute
  '/_authenticated/visao-futura': typeof AuthenticatedVisaoFuturaRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/api/analisar-fatura': typeof ApiAnalisarFaturaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analisar-fatura'
    | '/conferencia'
    | '/investimentos'
    | '/lancamentos'
    | '/parcelas'
    | '/visao-futura'
    | '/visao-geral'
    | '/api/analisar-fatura'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analisar-fatura'
    | '/conferencia'
    | '/investimentos'
    | '/lancamentos'
    | '/parcelas'
    | '/visao-futura'
    | '/visao-geral'
    | '/api/analisar-fatura'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analisar-fatura'
    | '/_authenticated/conferencia'
    | '/_authenticated/investimentos'
    | '/_authenticated/lancamentos'
    | '/_authenticated/parcelas'
    | '/_authenticated/visao-futura'
    | '/_authenticated/visao-geral'
    | '/api/analisar-fatura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAnalisarFaturaRoute: typeof ApiAnalisarFaturaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analisar-fatura': {
      id: '/_authenticated/analisar-fatura'
      path: '/analisar-fatura'
      fullPath: '/analisar-fatura'
      preLoaderRoute: typeof AuthenticatedAnalisarFaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conferencia': {
      id: '/_authenticated/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof AuthenticatedConferenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parcelas': {
      id: '/_authenticated/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof AuthenticatedParcelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-futura': {
      id: '/_authenticated/visao-futura'
      path: '/visao-futura'
      fullPath: '/visao-futura'
      preLoaderRoute: typeof AuthenticatedVisaoFuturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/analisar-fatura': {
      id: '/api/analisar-fatura'
      path: '/api/analisar-fatura'
      fullPath: '/api/analisar-fatura'
      preLoaderRoute: typeof ApiAnalisarFaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalisarFaturaRoute: typeof AuthenticatedAnalisarFaturaRoute
  AuthenticatedConferenciaRoute: typeof AuthenticatedConferenciaRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedParcelasRoute: typeof AuthenticatedParcelasRoute
  AuthenticatedVisaoFuturaRoute: typeof AuthenticatedVisaoFuturaRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalisarFaturaRoute: AuthenticatedAnalisarFaturaRoute,
  AuthenticatedConferenciaRoute: AuthenticatedConferenciaRoute,
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedParcelasRoute: AuthenticatedParcelasRoute,
  AuthenticatedVisaoFuturaRoute: AuthenticatedVisaoFuturaRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAnalisarFaturaRoute: ApiAnalisarFaturaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
